### ISSUE TITLE
PR Checklist

### ISSUE THREAD

**Issue by dsolovay** [dsolovay/Sitecore-Instance-Manager#32]
- [x] Works with Solr 4.x, ~~5.x, 6.x~~
- [x] Works with Solr at different URLS and ports (however, file system access is required to the instanceDir root directory)
- [x] ~~Works with all IOC options.~~  Remove any (e.g. Autofac, see #23) that don't work. Decided to focus on Castle exclusively.
- [x] Merge sitecore/Sitecore-Intance-Manager master
- [x] Rebase to single commit (or perhaps two, one for the If logic that got added to configuration, a second for the solr install feature itself
- [x] Add Solr notes to README.md

**Comment by dsolovay** [comment]
PR submitted: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/94
